### ISSUE TITLE
Add CI to test against downstream consumers of this project

### ISSUE THREAD

**Issue by dvzrv** [lsp-plugins/lsp-plugins-expander#3]
For testing purposes it would be very beneficial if this code was tested against e.g. the downstream distributions using it.
For Arch Linux I could help you to setup github CI to run a test build in an official docker container.

**Comment by sadko4u** [comment]
But why `expander` only? I think it is a good discussion for this project:
https://github.com/sadko4u/lsp-plugins/

**Comment by dvzrv** [comment]
Because that way you can test all components before you even attempt to use them in lsp-plugins.
Integrating at the last possible point has far less stability guarantees than doing it for all components.

**Comment by dvzrv** [comment]
Additionally, a stability guarantee is great to have not only for lsp-plugins as the consumer of all these modules, but for anyone else that wants to integrate it in their projects.

**Comment by sadko4u** [comment]
Yes, I understand. But this is very global project, I just think that the root project is the best place for discussions.

**Comment by dvzrv** [comment]
Closing in favor of https://github.com/sadko4u/lsp-plugins/issues/259
